### ISSUE TITLE
Assignment 2 - Question 2 : bash find and approaches which do not require a for loop

### ISSUE THREAD

**Issue by stefanmladjenovic** [BME1478H/Fall2020class#277]
Hello BME1478 TAs/instructors and classmates. 

I hope everyone is doing well. I am seeking help for question 2 on assignment 2. We need to create a for-loop to cycle through the directories and print out the directories which do not contain any .txt files. 

I was able to successfully print out the directories using the find function in the parent directory of where all the assignment-2 files are stored using the code below, however it prints out directories that do in fact contain .txt files (i.e the directory /20180204-01). My question here is: how come directories which contain .txt files appear when they should not?

```
 find . -type d \! -exec test -e '{}*.txt' \; -print 
```

I am now having trouble with converting this above commands into a for-loop. This is important because in question 3 we need to write a loop that renames all of the .txt files in each folder to notes.txt. 

As of now, I have the following parts/pieces (each code I save as a .sh file and wrote up using vim via Ubuntu (WSL)):

This allows me to print out the name of all of the sub-directories using a for-loop (cannot remember the exact source, but I believe it was from StackExchange. [This](https://stackoverflow.com/questions/9612090/how-to-loop-through-file-names-returned-by-find) is helpful):

```
#!/bin/bash
for i in */
do
	if [ -d "$i" ] 
	then
		echo "$i this is a directory"
	fi
done
```

I've also tried this code, but it only lists the sub-directories which are one level down (not the sub-sub-etc.-directories)
```
for dir in *
do
	set -- "$dir"/*.txt
	[ ! -e "$1" ] && printf '%s\n' "$dir"
done
```

I've also got the following code which I believe works but I'm not completely sure why. **From what I understand it looks the current directory (denoted by the asterisk) and then sets a temporary variable to $1 for files which have the .txt extension.** Lastly, it prints out the directory of every file that does not (denoted by exclamation point [!]) have the .txt extension.
 
```
for dir in *
do
	set -- "$dir"/*.txt
	[ ! -e "$1" ] && printf '%s\n' "$dir"
done
```

**Can you please advise me if I am on the right track?** I have spent many hours racking my mind through this and would sincerely appreciate any and all help. 

For question 3, where we have to write a loop that renames all of the note text files in each folder to: notes.txt, I'm thinking to rename the files by "moving them" within the same directory to effectively rename them, since you can rename a file while moving. Something along the lines of
`mv "$1" "notes.txt" ` 

**However, I'm not sure how to add this to the existing for-loop I have. Would I just add it on an additional line?** As in: 
```
for dir in *
do
	set -- "$dir"/*.txt
	[ ! -e "$1" ] && printf '%s\n' "$dir"
	mv "$1" "notes.txt"
done
```

Again any and all help is sincerely appreciated. 
[not sure why my code isn't being displayed/previewed as I wrote it with multi-lines. looking into this now. Advice on this is appreciated as well]

Cheers,
Stefan

**Comment by constructor-s** [comment]
Re: markdown formatting - You need to write the "`" on its own line 

`bash
for dir in *
do
    set -- "$dir"/*.txt
    [ ! -e "$1" ] && printf '%s\n' "$dir"
    mv "$1" "notes.txt"
done
`

**Comment by RayNele** [comment]
> how come directories which contain .txt files appear when they should not?

Hard to say since there's a lot of "fluff" in that command that needs to be referenced sections of the man pages (remember, you can 'man find' to read the manual for the command).

` find . -type d \! -exec test -e '{}*.txt' \; -print`

In your suggested command, it uses multiple arguments (`-type`, `-exec`, `test`, `-print') along with a '-e' tag (which is shorthand for something) in such a way that I can't actually understand what it does just by reading it.

Instead, I'll brief you through the workflow of how I would attempt this question so you can piece together a solution for problems in the future without relying to google. (Nothing against google and stackexchange, those are very helpful tools. but dumping a whole line of code with multiple arguments into a beginner's hand does not help with learning. Google should not be your first resort.)

I've created a test directory as follows:

```
.
+-- stefan1
|   +-- file.txt
+-- stefan2
|   +-- file.csv
+-- stefan3
|   +-- file2.txt
```
Lets start with a simple 'find' command, using the arguments we learned in lecture. To find all text files we use the '-name' modifier. 

`find -name '*.txt'`

which prints output:

`./stefan1/file.txt
./stefan3/file2.txt`

This returns the name and location of any txt files in its subdirectories. Since we only want the name of folders, we then need to find a way to manipulate the way the output is printed to include only the name of the folders. Here is where stackexchange would be helpful. You could also use the man pages here by looking up any '-print' modifiers that 'find' might have. In my case I've opted to use google, which returns me [this link](https://stackoverflow.com/questions/9597433/find-files-and-print-only-their-parent-directories) as the first thread on stackexchange.

Here you will see multiple people suggest '-printf '%h\n' which stands for print format. Now we can blindly paste this into your code for the answer.

`find -name '*.txt' -printf '%h\n'

But why does this work? If we return to the man pages, you'll find a section under '-printf' explaining all its related formatting. Here you'll see that '%h' will print the "Leading directories of the file's name (all but the last element)." which is exactly what we were looking for. If we do just '%h', it will print all the directories on one line like so:

`./stefan1./stefan3`

this is explained in the man page where it says "-printf does not add a newline at the end of the string"

this is why we use the `\n` newline character to get the intended output:

```./stefan1
./stefan3```


I would recommend (re-)attempting the remaining questions with the above workflow. Trial and error is your friend. Unlike wet lab experiments, these do not cost anything. Let me know if there are further questions after this.

**Comment by stefanmladjenovic** [comment]
Thank you Bill for the advice on markdown to format multi-line code. Much appreciated.

Thank you Ryan for your thorough reply and providing clear advice on how to solve this question in a systematic way. I have a much better understanding of how to proceed from here. Also thank you for editing my answer to clean-up the formatting of the code I entered. 

I will close this thread for now. Thank you both again, I sincerely appreciate it!

**Comment by stefanmladjenovic** [comment]
Quick question regarding grading of this assignment and future assignments. 

If it is possible to solve questions without using the approach suggested, will we still be awarded full marks? For example, in question 2 we are asked to use a for loop to find all the directories that do not contain a .txt file. If I created a way to do this WITHOUT using a for loop will I still be awarded full marks?
Thank you.

**Comment by RayNele** [comment]
For the sake of the assignment, I would like to see a solution which answers exactly what the question asks (It's good practice anyways, if you don't figure it out now, you'll be in trouble later when we work on python stuff). Your creativity is appreciated though.

**Comment by stefanmladjenovic** [comment]
Noted, will try again using for loop. 
I noticed that the approach I was trying didn't work. I set up a test environment to explain a new problem I have. 

Here is the general file structure. There is a folder called 'text' with only a .txt file in it; there is a folder called 'photo' with only a .jpg file in it; and there is a folder called 'mixed' that contains both a .txt file and a .jpg file:
```
.
+-- text
|   +-- t1.txt
+-- photo
|   +-- p1.jpg
+-- mixed
|   +-- t2.txt
|   +-- p2.jpg
```

For question 2, we need to write a loop that ONLY prints out the unique folders which are missing a note file (i.e. *.txt file). Ideally only the 'photo' directory would be a result. 

Here is what I currently have:

```
find . -not -name "*.txt" -printf "%h\n | sort -u" 
```

My output is:
``` 
./photo
./mixed
```

I understand why the photo directory appears, as intended (it contains a non-txt file, in this case a .jpg).
I also understand that the mixed directory is appearing since it contains both a non-txt file (i.e. .jpg) AND a .txt file file; the .jpg file is allowing mixed to appear when ideally it wouldn't. 

I am having trouble with finding a way to ONLY display the folders which have no .txt files inside (i.e. only the photo directory should appear, not mixed).** _**Do you have any advice on how to proceed from here?**_

In pseudocode, I'm trying to do the following 

```
find directories that contain non-txt files
if (folder contains both .txt and non-.txt files); then
>prune the directories containing txt files;
>echo the remaining non-txt folders 
done
```

I have played around with different find flags (from [here](https://man7.org/linux/man-pages/man1/find.1.html)), piping, etc. 

One of my piping attempts which didn't work was here. I tried to pipe all of the non-txt directories (i.e. mixed and photo) into another find command to ideally prune out the directories containing .txt files (i.e. remove the mixed folder) and thus get results which only explicitly contain non-.txt files (i.e. print 'photos'). Shown below:
```
find . -not -name "*.txt" -printf "%h\n" -print0 | xargs -0 -I{} find -prune -not -name "*.txt" | sort -u
```
Unfortunately this didn't work. 

Any advice on how to proceed from here is sincerely appreciated. Many thanks.

Cheers,
Stefan

**Comment by RayNele** [comment]
I'm away from the computer at the moment but I want to give you an answer anyways so that you can continue working on this. Let me know if this is not sufficient or if I missed any points (i skipped your post) and I can reanswer later tonight. 

The problem here I believe you have confused the difference between "print all folders containing non-text files" and "print all folders not containing a text file". As you have found out, the two are NOT the same. That is, a folder containing a non-text file may also contain a text file. 

To entertain your current non-loop approach there's only one way I am aware of which is a lot simpler than the current direction you're trying to go. So you are taking the prompt literally (print all directories which do not contain a text file). Sometimes a direct approach may not be the best, or even possible in this case. Instead you have to work with the tools you have available to get the job done with the least amount of work. That's the whole point of scripting right, to make your life easy and automate a bunch of menial tasks. 

In this case, we know how to list all directories, and we know how to list all directories that contain a text file (as per one of my previous comments). Why not take latter, and subtract it from the former? In other words, take the **difference** (wink wink) between the two outputs. I'll let you figure out the syntax for that one as not to spoil your fun.

**Comment by stefanmladjenovic** [comment]
Thank you Ryan, this is excellent advice! I'm so glad you were able to find the error in my reasoning for my approach and explain it in a clear and concise manner. I think my approach was also overly complicated.

I remember learning about and using the diff and comm (and join) commands for solving Q4 but I didn't think to use it for Q2. Great idea. (some more info [here](https://stackoverflow.com/questions/37170326/bash-comm-command-but-for-multiple-columns) for curious people reading; would recommend reading man pages for details).

I now have a way to compare the groups:

``` 
diff -r <(find . -type d) <(find . -name '*.txt' -printf "%h\n") 
``` 

or, using the comm command which gives the output in a different visual manner (more on diff vs. comm [here](https://www.networkworld.com/article/3279724/comparing-files-and-directories-with-diff-and-comm.html); again man pages have more details)

```
comm  <(find . -type d) <(find . -name '*.txt' -printf "%h\n")
```

As it stands, both these approaches do the job of printing the directories which do not contain .txt files. However I'm not sure what's the best way to combine this with a for loop.

One idea I had was to find the directories which contain .txt files, then store each directory as an individual element in an array (titled alltextdir). Next I store all directories into a separate array (stored in the array titled alldir). Lastly I would compare the elements of the array holding the directories (alldir) with the elements in the array which contain the .txt files (alltxtdir).

I was able to convert the above 'diff' into a script that uses arrays and compares them for differences. This works just as well for my purposes, but doesn't utilize a for-loop. This code is below: 

```
#!/bin/bash

alltextdir=( $( find -name '*.txt' -printf "%h\n" | sort -u ) )
#alltextdir is an array which stores the directories which contain .txt files

alldir=( $( find . -type d ) )
#alldir is an array which stores all directories

diff <(printf '%s\n' "${alltextdir[@]}") <(printf '%s\n' "${alldir[@]}")
```

I'm really trying to figure out some way to incorporate the for loop component. What I have right now doesn't work unfortunately and I'm not sure why. It is simply printing out all of the directories. I think it has to do with how I am using the "$f" variable in the for loop. Right now my thinking is:
```
#!/bin/bash

alltextdir=( $( find . -name '*.txt' -printf "%h\n" ) )
alldir=( $( find . -type d ) )
for f in "${alldir[@]}"
do
        diff <(printf '%s\n' "$f") <(printf '%s\n' "${alltextdir[@]}")
done
```

I also tried to take the above commands and only compare directories (i.e. if [ -d ]), but this gave the same output as the code immediately above. This makes sense because only directories would be stored in the array anyway. (just trying things out here). This script is below:
```
#!/bin/bash

alltextfiles=( $( find . -name '*.txt' -printf "%h\n" ) )
alldir=( $( find . -type d ) )
for f in "${alldir[@]}"
do
        if [ -d "$f" ];then
        diff <(printf '%s\n' "$f") <(printf '%s\n' "${alltextdir[@]}")
        fi
done
```

**I finally came upon a solution which works well, but I feel like I'm missing the point.** I'm essentially only incorporating a for-loop because it is being asked for the purpose of the assessment. Here I stored the difference in elements between the two arrays (i.e. 'alldir' subtract 'alltextdir') into a third array called 'difference'. Then I am printing out the elements in the third array; nothing is really being computed within the for-loop. (I found some help online [here](https://stackoverflow.com/questions/2312762/compare-difference-of-two-arrays-in-bash)).
Code below:

```
#!/bin/bash

alltextfiles=( $( find . -name '*.txt' -printf "%h\n" ) )
alldir=( $( find . -type d ) )
difference=(`echo ${alltextfiles[@]} ${alldir[@]} | tr ' ' '\n' | sort | uniq -u `)
for f in "${difference[@]}"
do
        (echo "$")
done
```
My apologies for the long post. Ultimately I am asking for advice/insight on how to incorporate the for loop in a more meaningful way because I feel like I am missing the point of it's purpose and I feel like I'm missing a valuable lesson in incorporating for loops. 

Any and all help is sincerely appreciated. Thank you for your patience and communication.

Cheers,
Stefan

**Comment by RayNele** [comment]
Right so as I mentioned before, the solution you have works on its own without a for loop. 
>To entertain your current non-loop approach

There's no reason to force the use of a for loop into your solution for the sake of the assignment. The code you have with diff does the job. 

You would need to start from scratch and try an entirely different approach with the for loop. A for loop can repeats a certain set of commands as many times as specified. This is PERFECT for parsing folders and performing some kind of task on each folder.

I know you've already spent a lot of time on this assignment, so to streamline your approach I can give you more direct instructions, in vague-ish psuedocode: 

1) for each directory
2) find text files (you can use the output of find as stdin, or save into a temp file)
3) if none are found (you don't actually have to use an if statement here, there are other ways to do it)
4) print the name of the directory OR append it to a text file and print the file at the end of the loop

keep in mind this is only one possible solution, if another solution you come up with differs from this but gets the job done, it's still correct. If you wanted to be snarky about it, you could add your code into a for loop repeating only once, and I wouldn't have a choice but to mark it correct. That solution doesn't show me that you understand for loops though and you'll be in trouble later when they need to be used regularly for assignments. 

But yes long answer short you definitely have the wrong idea about incorporating a for loop. I'm glad you figured out a non-loop approach though.

**Comment by zklaf** [comment]
Hi ,, This is my problem with rm command

Macintosh:~ zaidaldulaimi$ PWD
/Users/zaidaldulaimi
Macintosh:~ zaidaldulaimi$ ls
AceTax2011			Public
Applications			Samsung
Desktop				Sites
DipTrace			Ten Thumbs Students
Documents			java.log.11568
Downloads			java.log.757
Google Drive			matlab_crash_dump.11568-1
IMAGES				matlab_crash_dump.757-1
Library				qms-bmh1.bmp
Movies				qms-bmh2.bmp
Music				qms-bmh3.bmp
Pictures
Macintosh:~ zaidaldulaimi$ cd IMAGES
Macintosh:IMAGES zaidaldulaimi$ ls
DATA_ANALYSIS	IMAGES		__MACOSX	assignment-data
Macintosh:IMAGES zaidaldulaimi$ cd DATA_ANALYSIS
Macintosh:DATA_ANALYSIS zaidaldulaimi$ ls
DATA_ANALYSIS	assignment-data
Macintosh:DATA_ANALYSIS zaidaldulaimi$ rm -r *.jpg
rm: *.jpg: No such file or directory
Macintosh:DATA_ANALYSIS zaidaldulaimi$

**Comment by stefanmladjenovic** [comment]
Thank you (:
