### ISSUE TITLE
A2Q2 how to suppress 'find' output and only print what is in the if statement.

### ISSUE THREAD

**Issue by lisahofer** [BME1478H/Fall2020class#284]
I am trying to complete question 2 and my for loop is as follows. 

''' for f in $(ls assignment2-data); do
  if ! find assignment2-data/$f/*note*; then
    echo $f
  fi;
done;  '''

I output the correct folder names but while going through the loop it also prints out the path to the note file or that no such file exists. How do I suppress the output of the note finding and only print the folder name?

**Comment by stefanmladjenovic** [comment]
Hi Lisa, 
I'm also a student in BME1478 (: 

Perhaps the `dirname` command would help?

I'm not sure, but I also think you need to nest the `find` command in brackets since you're using it with an `if` statement. 
i.e. ``` if [[ $(! find assignment2-data/$f/note) ]] ```

This link might be helpful on nesting the ```find``` command in ```if``` : https://unix.stackexchange.com/questions/46541/how-can-i-use-bashs-if-test-and-find-commands-together 

I also believe the find command automatically prints out whichever results match the criteria you set. There might be a flag for `find` to quiet the output though. If I understand correctly, the `-q` flag in `grep`, as in `grep -q`, will quiet the output of `grep`. 

Best of luck and I hope this helps

**Comment by RayNele** [comment]
Why don't you try assigning it to a variable?

**Comment by lisahofer** [comment]
Thank you both! assigning a variable worked
