### ISSUE TITLE
q3 assignment2,I keep getting the error "mv: cannot stat '*.txt': No such file or directory" for my code "NAME=$(ls); for N in $NAME; do cd $N; VAR=$(find . -type f -name *.txt); if [ VAR = notes.txt ]; then mv notes.txt notes.txt; else mv *.txt notes.txt; fi; cd ..; although it works really well and changes all .txt to notes.txt

### ISSUE THREAD

**Issue by abdrabou1994** [BME1478H/Fall2020class#288]
q3 assignment2,I keep getting the error "mv: cannot stat '*.txt': No such file or directory" for my code "NAME=$(ls); for N in $NAME; do cd $N; VAR=$(find . -type f -name *.txt); if [ VAR = notes.txt ]; then mv notes.txt notes.txt; else mv *.txt notes.txt; fi; cd ..; although it works really well and changes all .txt to notes.txt
although it works really well and changes all .txt to notes.txt

**Comment by msaleh93** [comment]
Hey @abdrabou1994, I'm also a student but I think I know why this happens. You're ls command gives you a list of all of the directories. If you look at the contents of each directory, two of them don't contain .txt files (20180405-01 & 20180511-01). So in effect, you're trying to rename a non-existent *.txt into notes.txt

**Comment by msaleh93** [comment]
Also, note that your if statement `if [ VAR = notes.txt ]` will always evaluate to false. That's because you are comparing to see whether the string "VAR", and not the variable $VAR, is equal to "notes.txt". 

But even when that's fixed, it will still always evaluate as false. If before you run the if statement you do echo $VAR, you'll find that it prints out something along the lines of "./notes.txt" or "./noteslab.txt" depending on the current directory. This means your if statement should be `if [ $VAR = ./notes.txt ]`

Best way to double check your code is `echo` variables first before doing anything. And I find the verbatim option for mv and cp (the -v option) very helpful for trouble shooting stuff.

**Comment by abdrabou1994** [comment]
> 
> 
> Also, note that your if statement `if [ VAR = notes.txt ]` will always evaluate to false. That's because you are comparing to see whether the string "VAR", and not the variable $VAR, is equal to "notes.txt".
> 
> But even when that's fixed, it will still always evaluate as false. If before you run the if statement you do echo $VAR, you'll find that it prints out something along the lines of "./notes.txt" or "./noteslab.txt" depending on the current directory. This means your if statement should be `if [ $VAR = ./notes.txt ]`
> 
> Best way to double check your code is `echo` variables first before doing anything. And I find the verbatim option for mv and cp (the -v option) very helpful for trouble shooting stuff.

Thanks for the help M. Salah = ) really appreciate it!
